name: cbl
channels:
  - conda-forge
dependencies:
  - Cython=0.29.21
  - make
  - c-compiler=1.3.0
  - cxx-compiler=1.3.0
  - fortran-compiler=1.3.0
  - openmpi-mpifort
  - boost-cpp=1.77.0
  - gsl=2.5
  - fftw
  - cfitsio
  - ccfits
  - swig=4.0.1
  - python=3.6
  - six
  - numpy>=1.17
  - scipy>=1.3
  - pip>=19.0
