#!/bin/bash
make &&
make allExamples &&
cd Examples/vectors && ./vectors && cd ../.. &&
cd Examples/randomNumbers && ./randomNumbers && cd ../.. &&
cd Examples/distances && ./distances && cd ../.. &&
cd Examples/covsample && ./covsample && cd ../.. &&
cd Examples/fsigma8 && ./fsigma8 && cd ../.. &&
cd Examples/statistics/codes && ./prior && cd ../../.. &&
cd Examples/catalogue && ./catalogue && cd ../.. &&
cd Examples/clustering/codes && ./2pt_monopole && ./2pt_2D && ./2pt_jackknife && ./2pt_projected_jackknife && ./modelBias_2pt_projected && ./3pt && python 2pt_monopole.py && python 2pt_model.py && cd ../../.. && 
make doc && emacs Doc/WARNING_LOGFILE 
